### ISSUE TITLE
undefined method `each' for "<property>":String

### ISSUE THREAD

**Issue by niightly** [ruby-json-schema/json-schema#409]
Guys I'm trying to write some tests using a json matcher... but without luck 

## JSON Object from tests
```
{
   "search":{
      "entry":[
         {
            "dn":"Here is some fake data",
            "attribute":[
               {
                  "name":"description",
                  "value":[
                     "Fake Name"
                  ]
               },
               {
                  "name":"objectclass",
                  "value":[
                     "teste",
                     "top"
                  ]
               }
            ]
         }
      ]
   }
}
```
## Schema to be validated
```
class FakeObject
  def self.schema
    {
      type: 'object',
      required: 'search',

      properties: {
        search: {
          type: 'object',
          required: 'entry',

          properties: {
            entry: {
              type: 'array',

              items: {
                type: 'object',
                required: %w[dn attribute],

                properties: {
                  dn: { type: 'string' },
                  attribute: {
                    type: 'array',

                    items: {
                      type: 'object',
                      required: %w[name value],

                      properties: {
                        name: { type: 'string' },
                        value: { type: 'array' }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  end
end
```
## Custom Matcher
```
RSpec::Matchers.define :match_response_schema do |schema|
	match do |response|
		if schema.include?('_')
			class_name = schema.split('_')
			class_name = class_name.collect(&:capitalize)
			schema = class_name.join('')
		end

		JSON::Validator.validate!("#{schema}".safe_constantize.schema, response, strict: true)
	end
end
```

## RSpec Test
```
RSpec.describe BluepagesService do
	describe '#Positive scenarios' do
		it 'Fetch data from FakeObject' do
			data = FakeService.fetch_data
			expect(data).to match_response_schema('FakeObject')
		end
	end
end
```

# Getting this Error

```
1) FakeService#Positive scenarios Fetch data from FakeObject
     Failure/Error: JSON::Validator.validate!("#{schema}".safe_constantize.schema, response, strict: true)

     NoMethodError:
       undefined method `each' for "search":String
     # /Users/thiagogs/.rvm/gems/ruby-2.4.1/gems/json-schema-2.8.0/lib/json-schema/attributes/required.rb:12:in `validate'
     # /Users/thiagogs/.rvm/gems/ruby-2.4.1/gems/json-schema-2.8.0/lib/json-schema/schema/validator.rb:25:in `block in validate'
     # /Users/thiagogs/.rvm/gems/ruby-2.4.1/gems/json-schema-2.8.0/lib/json-schema/schema/validator.rb:23:in `each'
     # /Users/thiagogs/.rvm/gems/ruby-2.4.1/gems/json-schema-2.8.0/lib/json-schema/schema/validator.rb:23:in `validate'
     # /Users/thiagogs/.rvm/gems/ruby-2.4.1/gems/json-schema-2.8.0/lib/json-schema/schema.rb:33:in `validate'
     # /Users/thiagogs/.rvm/gems/ruby-2.4.1/gems/json-schema-2.8.0/lib/json-schema/validator.rb:113:in `validate'
     # /Users/thiagogs/.rvm/gems/ruby-2.4.1/gems/json-schema-2.8.0/lib/json-schema/validator.rb:254:in `validate!'
     # ./spec/support/api_schema_matcher.rb:11:in `block (2 levels) in <top (required)>'
     # ./spec/services/fake_service_spec.rb:7:in `block (3 levels) in <top (required)>'

Finished in 2.96 seconds (files took 2.46 seconds to load)
```

## Versions
* Rails 5.1.6
* ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin17]

## Gems installed
I'm not sure which one will be important on this issue, if you need more I will be happy to update it.

* spec (3.6.0)
* rspec-core (3.7.1, 3.6.0)
* rspec-expectations (3.7.0, 3.6.0)
* rspec-html-matchers (0.9.1)
* rspec-mocks (3.7.0, 3.6.0)
* rspec-rails (3.7.2, 3.6.1)
* rspec-support (3.7.1, 3.6.0)
* json (2.1.0, default: 2.0.2)
* json-schema (2.8.0)

**Comment by niightly** [comment]
Guys anyone? Is this repo active?

**Comment by niightly** [comment]
found the problem... Looks like the required MUST be an array even when there is only one property on it.
