### ISSUE TITLE
$ref paths relative to working directory don't work if containing schema was itself referenced

### ISSUE THREAD

**Issue by reitzig** [ruby-json-schema/json-schema#411]
Consider the following folder structure with files as given in [this Gist](https://gist.github.com/reitzig/9fd7c1c2718b46bb43dcd3506ec3437a):

```
.
├── example.json
├── schemas
│   ├── more
│   │   ├── schemaB.json
│   │   └── schemaC.json
│   └── stuff
│       └── schemaA.json
└── validate.rb
```

_Expected:_ Running `validate.rb` prints `0`.

_Actual:_ 

```
Traceback (most recent call last):
	25: from ./validate.rb:8:in `<main>'
	<snip>
/home/user/.gem/ruby/2.5.0/gems/json-schema-2.8.0/lib/json-schema/schema/reader.rb:136:in `rescue in read_file': 
    Read of file at /<snip>/schematest/schemas/more/schemas/more/schemaC.json failed (JSON::Schema::ReadFailed)
```

Clearly, the path is assembled incorrectly: 

 - The reference in `schemaA.json` to `schemaB.json` is correctly interpreted as relative to the working directory.
 - The reference  in `schemaB.json` to `schemaC.json is interpreted as relative to `schemaB.json`.

This is inconsistent.

Is there a workaround? Changing the `$ref` paths is not an option if schemas are referenced at different depths.

**Comment by reitzig** [comment]
I traced the problem down to `Addressable::URI.join` being called on a UUID for references in the top-level schema, but on a real path (that of the top-level schema) for low levels.
cf. [JSON::Util::URI.absolutize_ref](https://github.com/ruby-json-schema/json-schema/blob/2f95d53d62428d603601a1346d6e12a70e7a505d/lib/json-schema/util/uri.rb#L26)

Then, the dir-part absolute path of the top-level schema and the relative path to the schema are joined together without considering the overlap.

Not sure what the correct fix here is.

 * Option 1: Resolve the URI of the top-level schema in the beginning.  
   --> All URIs are relative to the current schema.
 * Option 2: Join with the working directory, not the `ref` URI (the one of the current schema).  
   --> All URIs are relative to the working directory.

**Comment by reitzig** [comment]
**Workaround:**  Call `validate` with the filename of the top-level schema instead of its content.

Then, all URIs are treated in the same way (Option 1).
